# .rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Layout/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Layout/IndentationWidth:
  Width: 2

Metrics/MethodLength:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf
