database_config:
  # Type of database used in the project
  database_type: sqlite   # or 'mongodb'

  sqlite_database:
    # Path to the SQLite database file
    db_file: db/local_database.sqlite
    # Additional parameters (optional)
    timeout: 5000   # Connection timeout in milliseconds
    pool_size: 5    # Connection pool size

  mongodb_database:
    # MongoDB URI
    uri: mongodb://localhost:27017
    db_name: my_database  # MongoDB database name
